"use strict";
const RSVP_NUMBER="34641911387";
const $=id=>document.getElementById(id),audio=$('music'),musicButton=$('music-button'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
function syncMusic(){musicButton.textContent=audio.paused?'♫':'Ⅱ';musicButton.setAttribute('aria-label',audio.paused?'Reproducir música':'Pausar música');musicButton.setAttribute('aria-pressed',String(!audio.paused))}audio.addEventListener('play',syncMusic);audio.addEventListener('pause',syncMusic);musicButton.onclick=()=>audio.paused?audio.play().catch(syncMusic):audio.pause();
$('open').onclick=()=>{$('open').disabled=true;audio.volume=.6;audio.play().catch(syncMusic);$('cover').classList.add('opening');setTimeout(()=>{$('cover').hidden=true;$('invitation').hidden=false;musicButton.hidden=false;scrollTo(0,0);document.querySelector('.hero h1').focus({preventScroll:true});if(!reduced.matches&&'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>{e.classList.add('waiting');observer.observe(e)})}},reduced.matches?0:1300)};
const offset=(new Date(2026,9,1).getDay()+6)%7;for(let i=0;i<31+offset;i++){const c=document.createElement('span'),day=i-offset+1;if(day>0){c.textContent=day;if(day===24){c.className='selected';c.setAttribute('aria-label','24 de octubre, nuestra boda')}}$('calendar-days').append(c)}
const target=Date.parse('2026-10-24T19:00:00+02:00');function tick(){const t=Math.max(0,Math.floor((target-Date.now())/1000));[Math.floor(t/86400),Math.floor(t/3600)%24,Math.floor(t/60)%60,t%60].forEach((v,i)=>$(['days','hours','minutes','seconds'][i]).textContent=String(v).padStart(2,'0'));if(!t)$('countdown-note').textContent='¡Llegó el día de celebrar nuestro amor!'}tick();setInterval(tick,1000);
if(RSVP_NUMBER){$('rsvp-actions').hidden=false;$('rsvp-pending').hidden=true;$('confirm').href='https://wa.me/'+RSVP_NUMBER+'?text='+encodeURIComponent('Hola, queremos confirmar asistencia a la boda de Eddy y Daniela. Nombre:   Número de asistentes: ');$('questions').href='https://wa.me/'+RSVP_NUMBER+'?text='+encodeURIComponent('Hola, tengo una consulta sobre la boda de Eddy y Daniela.');}
for(let i=0;i<28;i++){const s=document.createElement('i');s.className=i%3===0?'soft':'strong';const x=i%2===0?2+(i*7)%19:79+(i*3)%19;s.style.cssText=`--x:${x}%;--y:${(i*23+3)%100}%;--size:${i%3===0?5:12+i%4*4}px;--time:${3+i%5*.8}s;--delay:${-i*.71}s`;$('sparkles').append(s)}document.addEventListener('visibilitychange',()=>$('sparkles').classList.toggle('paused',document.hidden));$('back-top').onclick=()=>scrollTo({top:0,behavior:reduced.matches?'instant':'smooth'});
